javier_soporte:
    resource: "@GEASoporteBundle/Resources/config/routing.yml"
    prefix:   /soporte/
    
pagina_inicio:
    path:    /
    defaults: { _controller: GEASoporteBundle:Default:portada }
_pagina_inicio:
    path:    /inicio/
    defaults: { _controller: GEASoporteBundle:Default:portada }
    
#Autenticacion y salida
usuario_logout:
    path: /usuario/logout/
usuario_login:
    path: /usuario/login
    defaults: { _controller: GEASoporteBundle:Login:login }
usuario_pre_logout:
    path: /usuario/pre/logout/
    defaults: { _controller: GEASoporteBundle:Login:preLogout }