generator: admingenerator.generator.propel
params:
    model: GEA\SoporteBundle\Model\Usuario
    namespace_prefix: GEA
    concurrency_lock: ~
    bundle_name: SoporteBundle
    pk_requirement: ~
    fields:
        fecha_nacimiento:
            formType: text
            addFormOptions:
                read_only: true
                attr:
                    class: "datepicker"
                    data-format: "yyyy-mm-dd"
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Usarios
            display: [username, email]
            actions:
                new: ~
            object_actions:
                edit: ~
                perfiles:
                    route: editar_perfiles_usuario
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: Nuevo usuario
            display: [nombre, apellido, username, email, direccion, fecha_nacimiento, EstadoUsuario]
            actions:
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Editando el usuario \"%object%\"|{ %object%: Usuario.username }|"
            display: [nombre, apellido, username, email, direccion, fecha_nacimiento, EstadoUsuario]
            actions:
                save-and-list: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Usuario.username }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
